[pytest]
# handle whitespace sequences equally and do not make a
# difference between u"a" and "a" in output.
doctest_optionflags = NORMALIZE_WHITESPACE ALLOW_UNICODE
addopts = --doctest-modules --doctest-glob='*.rst'
          tests/ diceware_list/ README.rst

[tox]
envlist =py27, py34, py35, py36, py37, py38, pypy, pypy3, flake8, cov

[testenv]
setenv= LANG=
usedevelop=True
deps=pytest
commands=
  py.test

[testenv:flake8]
deps=flake8
commands=flake8 --ignore=E121,E123,E126,E226,E24,E704,W503,W504,W605 diceware_list setup.py tests

[testenv:cov]
basepython=python3.6
deps=
  coverage
commands=
  coverage erase
  coverage run setup.py test
  coverage report --include='diceware_list*,setup.py' \
                  -m --fail-under=100
